#pragma once

#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(APP_EVENT_BASE);

enum AppEvent
{
    APP_ETHERNET_MGMT_INTERFACE_CONNECTED,
    APP_ETHERNET_MGMT_INTERFACE_DISCONNECTED,
    APP_ETHERNET_MGMT_INTERFACE_GOT_IP,
    APP_ETHERNET_MGMT_INTERFACE_LOST_IP
};

ESP_EVENT_DECLARE_BASE(SNIFFER_EVENT_BASE);

enum SnifferEvent
{
    SNIFFER_STARTED,
    SNIFFER_STOPPED,
    SNIFFER_RECEIVED_PACKET
};

ESP_EVENT_DECLARE_BASE(MQTT_EVENT_BASE);

enum MQTTEvent {
    MQTT_CONNECTED,
    MQTT_DISCONNECTED
};
